import React from "react";
import TabItem from "./TabItem";
export { TabItem };
import "./index.scss";
declare const _default: React.ComponentType<Omit<{
    clearOnChange?: boolean | undefined;
    children?: any;
    contentPadding?: string | undefined;
    headerItemExternalCls?: string | undefined;
    extraContentCls?: string | undefined;
    contentHeight?: any;
    extraData?: any;
    showExtraContent?: boolean | undefined;
    commonExtraContent?: any;
    onLabelClick?: any;
    activeIndex?: number | undefined;
    activeLabelColor?: string | undefined;
    tabStyle?: "common" | "bootstrap" | undefined;
    lineaGradient?: string | undefined;
}, keyof import("react-i18next").WithTranslation<N, undefined>> & import("react-i18next").WithTranslationProps>;
export default _default;
