import React from "react";
import TableCell from "./TableCell";
import "./index.scss";
export { TableCell };
declare const _default: React.ComponentType<Omit<{
    data: any;
    maxWidth?: any;
    children?: any;
    eidtable?: boolean | undefined;
    width?: any;
    textPosition?: "center" | "start" | "end" | "justify" | undefined;
    verticalAlign?: "middle" | "top" | "bottom" | undefined;
    onEditOK?: ((data: any) => void) | undefined;
    defaultChecked?: any;
    headerFontWeight?: "bold" | "normal" | undefined;
    tableBgc?: any;
    tableRef?: any;
    activeId?: string | number | undefined;
    showIndex?: boolean | undefined;
    single?: boolean | undefined;
    id?: string | undefined;
    trPointer?: boolean | undefined;
    collection?: boolean | undefined;
    collapse?: boolean | undefined;
    expandAll?: boolean | undefined;
    size?: "lg" | "sm" | undefined;
    tableStriped?: boolean | undefined;
    tableBorderd?: boolean | undefined;
    tableBorderless?: boolean | undefined;
    headColor?: "light" | "dark" | undefined;
    tableResponsive?: "lg" | "sm" | "md" | "xl" | "xxl" | undefined;
    headSticky?: boolean | undefined;
    headTextColor?: string | undefined;
    headBGC?: any;
    divider?: boolean | undefined;
    maxHeight?: string | undefined;
    minHeight?: string | undefined;
    onRowDoubleClick?: ((row: any) => void) | undefined;
    onRowClick?: ((row: any) => void) | undefined;
    onClearSelected?: (() => void) | undefined;
}, keyof import("react-i18next").WithTranslation<N, undefined>> & import("react-i18next").WithTranslationProps>;
export default _default;
