import React from "react";
import TableCell from "./TableCell";
import "./index.scss";
export { TableCell };
export declare const recursiveGenerateTableHeaderRows: (columns: any[], newRows?: any[]) => any[];
declare const _default: React.ComponentType<Omit<{
    showTip?: boolean | undefined;
    collapse?: boolean | undefined;
    maxWidth?: any;
    eidtable?: boolean | undefined;
    align?: "center" | "start" | "end" | "justify" | undefined;
    children?: any;
    data: any;
    checkAll?: boolean | undefined;
    tdPadding?: string | undefined;
    clickChecked?: boolean | undefined;
    showHeader?: boolean | undefined;
    defaultCheckedList?: any;
    headerFontWeight?: "bold" | "normal" | undefined;
    tableWidth?: any;
    tableBGC?: any;
    tableRef?: any;
    activeId?: string | number | undefined;
    showIndex?: boolean | undefined;
    multiple?: boolean | undefined;
    id?: string | undefined;
    trPointer?: boolean | undefined;
    collection?: boolean | undefined;
    expandAll?: boolean | undefined;
    size?: "lg" | "sm" | undefined;
    columns?: any;
    propsData?: any;
    tableHover?: boolean | undefined;
    tableStriped?: boolean | undefined;
    tableBorderd?: boolean | undefined;
    tableBorderless?: boolean | undefined;
    headColor?: "light" | "dark" | undefined;
    captionContent?: any;
    captionPosition?: "top" | "bottom" | undefined;
    tableResponsive?: "lg" | "sm" | "md" | "xl" | "xxl" | undefined;
    headSticky?: boolean | undefined;
    headTextColor?: string | undefined;
    headBGC?: any;
    divider?: boolean | undefined;
    maxHeight?: string | undefined;
    minHeight?: string | undefined;
    onRowDoubleClick?: ((row: any) => void) | undefined;
    onRowClick?: ((row: any) => void) | undefined;
}, keyof import("react-i18next").WithTranslation<N, undefined>> & import("react-i18next").WithTranslationProps>;
export default _default;
