import React from "react";
import "./index.scss";
interface ListGroupProps {
    lisgGroupStyle?: React.CSSProperties;
    listGroupClassName?: string;
    focusedIndex?: any;
    actRef?: any;
    buttonClassName?: string;
    buttonStyle?: React.CSSProperties;
    activeId?: string | number;
    showBorderRadius?: boolean;
    showBorder?: boolean;
    buttonWidth?: any;
    canCancel?: boolean;
    multiple?: boolean;
    itemHeight?: number;
    columnMaxHeight?: number;
    lineBreak?: boolean;
    listPerColumn?: number;
    height?: any;
    maxHeight?: any;
    activeOnClick?: boolean;
    externalClassName?: string;
    noWrap?: boolean;
    data?: any[];
    activeList?: any;
    labelKey?: string;
    valueKey?: string;
    type?: string;
    onItemClick?: (item: any, index: number) => void;
    onItemDoubleClick?: (item: any, index: number) => void;
    render?: (item: any, labelKey: string, valueKey: string) => any;
    onEnter?: (item: any, index: number) => void;
}
declare const ListGroup: ({ lisgGroupStyle, listGroupClassName, focusedIndex, actRef, buttonClassName, buttonStyle, activeId, showBorderRadius, showBorder, buttonWidth, canCancel, multiple, itemHeight, columnMaxHeight, lineBreak, listPerColumn, height, maxHeight, activeOnClick, externalClassName, noWrap, data, activeList: selectList, labelKey, valueKey, type, render, onItemClick, onItemDoubleClick, onEnter, }: ListGroupProps) => React.JSX.Element;
export default ListGroup;
