import React from "react";
import "./index.scss";
interface ListGroupProps {
    activeId?: string | number;
    showBorderRadius?: boolean;
    showBorder?: boolean;
    buttonWidth?: any;
    canCancel?: boolean;
    multiple?: boolean;
    itemHeight?: number;
    columnMaxHeight?: number;
    lineBreak?: boolean;
    listPerColumn?: number;
    height?: any;
    maxHeight?: any;
    activeOnClick?: boolean;
    externalClassName?: string;
    noWrap?: boolean;
    defaultSelectFirst?: boolean;
    data?: any[];
    activeList?: any;
    labelKey?: string;
    valueKey?: string;
    type?: string;
    onItemClick?: (item?: any) => void;
    onItemDoubleClick?: (item?: any) => void;
    render?: (item: any, labelKey: string, valueKey: string) => any;
}
declare const ListGroup: ({ activeId, showBorderRadius, showBorder, buttonWidth, canCancel, multiple, itemHeight, columnMaxHeight, lineBreak, listPerColumn, height, maxHeight, activeOnClick, externalClassName, noWrap, defaultSelectFirst, data, activeList: selectList, labelKey, valueKey, type, render, onItemClick, onItemDoubleClick, }: ListGroupProps) => React.JSX.Element;
export default ListGroup;
