import React from "react";
import "./index.scss";
export interface InputProps {
    type?: "text" | "datetime-local" | "date" | "time";
    name?: string;
    defaultValue?: any;
    size?: "large" | "middle" | "small" | undefined;
    className?: string;
    prefixContent?: any;
    suffixContent?: any;
    placeholder?: string;
    style?: any;
    disabled?: boolean;
    children?: any;
    transparent?: boolean;
    setFormItemValue?: (value: any) => void;
    onClick?: (e: React.MouseEvent<HTMLInputElement, MouseEvent>, ...args: any) => void;
    onFocus?: (e: React.FocusEvent<HTMLInputElement, Element>, ...args: any) => void;
    onBlur?: (e: React.FocusEvent<HTMLInputElement, Element>, ...args: any) => void;
    onChange?: (value: any, ...args: any) => void;
    onIconClick?: (value: string) => void;
}
declare const _default: React.ComponentType<Omit<{
    style?: any;
    type?: "text" | "datetime-local" | "date" | "time" | undefined;
    name?: string | undefined;
    defaultValue?: any;
    size?: "large" | "middle" | "small" | undefined;
    className?: string | undefined;
    prefixContent?: any;
    suffixContent?: any;
    placeholder?: string | undefined;
    disabled?: boolean | undefined;
    children?: any;
    transparent?: boolean | undefined;
    setFormItemValue?: ((value: any) => void) | undefined;
    onClick?: ((e: React.MouseEvent<HTMLInputElement, MouseEvent>, ...args: any) => void) | undefined;
    onFocus?: ((e: React.FocusEvent<HTMLInputElement, Element>, ...args: any) => void) | undefined;
    onBlur?: ((e: React.FocusEvent<HTMLInputElement, Element>, ...args: any) => void) | undefined;
    onChange?: ((value: any, ...args: any) => void) | undefined;
    onIconClick?: ((value: string) => void) | undefined;
}, keyof import("react-i18next").WithTranslation<N, undefined>> & import("react-i18next").WithTranslationProps>;
export default _default;
